# Generated by Django 3.2.5 on 2021-07-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_main_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='fb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='tw',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='yt',
            field=models.URLField(blank=True, null=True),
        ),
    ]
